"""
Evaluate a trained Phase 0.5 dual-head checkpoint on any MirrorSceneDataset split.

This script is for the cross-domain smoke gate. It does not train. It loads a
dual-head checkpoint and reports whether first-surface and secondary-path heads
still recover both layers on the target split.
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

# MetaX C500 compatibility: avoid torch._dynamo -> Triton backend discovery.
os.environ.setdefault("TORCHDYNAMO_DISABLE", "1")
os.environ.setdefault("TORCH_COMPILE_DISABLE", "1")

import numpy as np
import torch
from torch.utils.data import DataLoader


SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "src" / "third_party" / "vggt"))
sys.path.insert(0, str(SCRIPT_DIR))

from data.mirror_scene_dataset import MirrorSceneDataset, collate_fn
from train_dual_head_baseline import DualHeadVGGT, MetricAccumulator, choose_device


TARGET_METRICS = [
    "dual_primary_vs_first_nl",
    "dual_secondary_vs_secondary_nl",
    "dual_two_layer_mean_nl",
]


def load_dual_checkpoint(model, checkpoint_path, device):
    # PyTorch 2.6 defaults torch.load(..., weights_only=True), which rejects
    # full training checkpoints containing optimizer metadata. These checkpoints
    # are generated by this repo, so loading trusted local artifacts with
    # weights_only=False is intentional.
    ckpt = torch.load(checkpoint_path, map_location=device, weights_only=False)
    state = ckpt.get("model", ckpt)
    cleaned = {key.removeprefix("module."): value for key, value in state.items()}
    missing, unexpected = model.load_state_dict(cleaned, strict=False)
    return {
        "missing": len(missing),
        "unexpected": len(unexpected),
        "missing_sample": missing[:10],
        "unexpected_sample": unexpected[:10],
        "checkpoint_epoch": ckpt.get("epoch"),
        "checkpoint_loss": ckpt.get("loss"),
    }


def load_reference_metrics(path):
    if not path:
        return None
    ref = json.loads(Path(path).read_text(encoding="utf-8"))
    return ref.get("metrics", ref)


@torch.no_grad()
def evaluate_checkpoint(model, loader, device, mask_threshold=0.5):
    model.eval()
    metrics = {
        "vggt_primary_vs_first_l": MetricAccumulator(),
        "vggt_primary_vs_first_nl": MetricAccumulator(),
        "vggt_primary_vs_secondary_nl": MetricAccumulator(),
        "dual_primary_vs_first_l": MetricAccumulator(),
        "dual_primary_vs_first_nl": MetricAccumulator(),
        "dual_secondary_vs_secondary_nl": MetricAccumulator(),
        "dual_secondary_vs_first_nl": MetricAccumulator(),
        "dual_mask_acc_valid_first": MetricAccumulator(),
    }
    stats = {
        "valid_first_pixels": 0,
        "gt_nl_pixels": 0,
        "pred_nl_pixels_valid_first": 0,
    }

    for batch in loader:
        images = batch["images"].to(device)
        gt_first = batch["world_points"].to(device)
        gt_secondary = batch["world_points_secondary"].to(device)
        mask_first = batch["point_masks"].to(device)
        mask_secondary = batch["point_masks_secondary"].to(device)
        mask_l = mask_first & ~mask_secondary
        mask_nl = mask_first & mask_secondary

        pred = model(images)
        vggt_first = pred["vggt_world_points"]
        primary = pred["primary_points"]
        secondary = pred["secondary_points"]
        pred_mask = pred["mask_pred"] > mask_threshold

        metrics["vggt_primary_vs_first_l"].add_l2(vggt_first, gt_first, mask_l)
        metrics["vggt_primary_vs_first_nl"].add_l2(vggt_first, gt_first, mask_nl)
        metrics["vggt_primary_vs_secondary_nl"].add_l2(vggt_first, gt_secondary, mask_nl)
        metrics["dual_primary_vs_first_l"].add_l2(primary, gt_first, mask_l)
        metrics["dual_primary_vs_first_nl"].add_l2(primary, gt_first, mask_nl)
        metrics["dual_secondary_vs_secondary_nl"].add_l2(secondary, gt_secondary, mask_nl)
        metrics["dual_secondary_vs_first_nl"].add_l2(secondary, gt_first, mask_nl)
        metrics["dual_mask_acc_valid_first"].add_binary_acc(pred_mask, mask_secondary, mask_first)

        stats["valid_first_pixels"] += int(mask_first.sum().item())
        stats["gt_nl_pixels"] += int(mask_nl.sum().item())
        stats["pred_nl_pixels_valid_first"] += int((pred_mask & mask_first).sum().item())

    values = {key: value.mean() for key, value in metrics.items()}
    counts = {key: value.count for key, value in metrics.items()}

    if np.isfinite(values["dual_primary_vs_first_nl"]) and np.isfinite(values["dual_secondary_vs_secondary_nl"]):
        values["dual_two_layer_mean_nl"] = 0.5 * (
            values["dual_primary_vs_first_nl"] + values["dual_secondary_vs_secondary_nl"]
        )
        counts["dual_two_layer_mean_nl"] = min(
            counts["dual_primary_vs_first_nl"],
            counts["dual_secondary_vs_secondary_nl"],
        )

    valid = max(stats["valid_first_pixels"], 1)
    stats["gt_nl_fraction_valid_first"] = stats["gt_nl_pixels"] / valid
    stats["pred_nl_fraction_valid_first"] = stats["pred_nl_pixels_valid_first"] / valid
    stats["pred_to_gt_nl_fraction_ratio"] = stats["pred_nl_fraction_valid_first"] / max(
        stats["gt_nl_fraction_valid_first"],
        1e-12,
    )
    return {"metrics": values, "counts": counts, "coverage": stats}


def finite_number(value):
    return isinstance(value, (int, float)) and np.isfinite(value)


def compare_to_reference(
    metrics,
    coverage,
    reference_metrics,
    max_reference_ratio,
    min_nl_pixels,
    min_pred_to_gt_nl_fraction_ratio,
):
    if coverage["gt_nl_pixels"] < min_nl_pixels:
        return {
            "smoke_verdict": "inconclusive",
            "reason": f"Only {coverage['gt_nl_pixels']} GT NL pixels; need at least {min_nl_pixels}.",
        }

    if coverage["pred_to_gt_nl_fraction_ratio"] < min_pred_to_gt_nl_fraction_ratio:
        return {
            "smoke_verdict": "fail",
            "reason": "Predicted NL coverage collapsed relative to GT NL coverage.",
            "min_pred_to_gt_nl_fraction_ratio": min_pred_to_gt_nl_fraction_ratio,
        }

    if not reference_metrics:
        return {
            "smoke_verdict": "inconclusive",
            "reason": "No reference JSON was provided.",
        }

    ratios = {}
    missing = []
    for key in TARGET_METRICS:
        current = metrics.get(key)
        reference = reference_metrics.get(key)
        if not finite_number(current) or not finite_number(reference) or reference <= 0:
            missing.append(key)
            continue
        ratios[key] = current / reference

    if missing:
        return {
            "smoke_verdict": "inconclusive",
            "reason": f"Missing or non-finite metrics: {', '.join(missing)}.",
            "ratios_vs_reference": ratios,
        }

    passed = all(value <= max_reference_ratio for value in ratios.values())
    return {
        "smoke_verdict": "pass" if passed else "fail",
        "max_reference_ratio": max_reference_ratio,
        "ratios_vs_reference": ratios,
    }


def empty_result(args, device):
    return {
        "created": datetime.now().isoformat(timespec="seconds"),
        "status": "blocked-data",
        "reason": "No scene_* directories with scene_meta.json were found.",
        "data_dir": args.data_dir,
        "checkpoint": args.checkpoint,
        "device": str(device),
        "required_dataset_contract": [
            "scene_XXXXX/scene_meta.json",
            "scene_XXXXX/rgb_000.png ... rgb_NNN.png",
            "scene_XXXXX/depth_first_000.npy ... depth_first_NNN.npy",
            "scene_XXXXX/depth_secondary_000_mirror00.npy ... depth_secondary_NNN_mirror00.npy",
            "scene_XXXXX/camera_000.npz ... camera_NNN.npz with intrinsic and extrinsic arrays",
        ],
    }


def write_json(path, result):
    if not path:
        return
    output_json = Path(path)
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(result, indent=2), encoding="utf-8")


def metric_line(key, output):
    value = output["metrics"].get(key, float("nan"))
    count = output["counts"].get(key, 0)
    if finite_number(value):
        rendered = f"{value:.6f}"
    else:
        rendered = "nan"
    return f"| `{key}` | {rendered} | {count} |"


def write_note(path, output):
    if not path:
        return
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if output.get("status") == "blocked-data":
        lines = [
            "---",
            "tags: [experiment, phase-0-5, dual-head, cross-domain, blocked-data]",
            f"created: {output['created']}",
            "status: blocked-data",
            "---",
            "",
            "# Phase 0.5 Dual-Head Cross-Domain Smoke",
            "",
            "## Status",
            "",
            "Blocked: no valid `MirrorSceneDataset` scenes were found at the requested data directory.",
            "",
            "## Requested Setup",
            "",
            f"- Data: `{output['data_dir']}`",
            f"- Checkpoint: `{output['checkpoint']}`",
            f"- Device: `{output['device']}`",
            "",
            "## Required Dataset Contract",
            "",
        ]
        lines.extend(f"- `{item}`" for item in output["required_dataset_contract"])
        lines.extend([
            "",
            "## Claim Impact",
            "",
            "No cross-domain evidence was produced. This does not support or refute the layered claim.",
            "",
        ])
        path.write_text("\n".join(lines), encoding="utf-8")
        return

    lines = [
        "---",
        "tags: [experiment, phase-0-5, dual-head, cross-domain]",
        f"created: {output['created']}",
        f"status: {output['status']}",
        "---",
        "",
        "# Phase 0.5 Dual-Head Cross-Domain Smoke",
        "",
        "## Setup",
        "",
        f"- Data: `{output['data_dir']}`",
        f"- Scenes: `{output['num_scenes']}`",
        f"- Views per scene: `{output['num_views']}`",
        f"- Checkpoint: `{output['checkpoint']}`",
        f"- Device: `{output['device']}`",
        f"- Checkpoint load: missing `{output['checkpoint_load']['missing']}`, unexpected `{output['checkpoint_load']['unexpected']}`",
        "",
        "## Metrics",
        "",
        "| Metric | Value | Count |",
        "|---|---:|---:|",
    ]
    for key in output["metrics"].keys():
        lines.append(metric_line(key, output))

    lines.extend(["", "## Derived"])
    for key, value in output.get("derived", {}).items():
        if key == "ratios_vs_reference":
            continue
        lines.append(f"- `{key}`: `{value}`")

    ratios = output.get("derived", {}).get("ratios_vs_reference")
    if ratios:
        lines.extend(["", "## Ratios vs In-Domain Reference", ""])
        for key, value in ratios.items():
            lines.append(f"- `{key}`: `{value:.3f}x`")

    lines.extend([
        "",
        "## Gate Decision",
        "",
        f"- Smoke verdict: `{output['derived']['smoke_verdict']}`",
        "",
        "A pass only means the dual-head checkpoint did not collapse on this target split under the same synthetic-format metric. It does not prove real-data generalization.",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


@torch.no_grad()
def run(args):
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    device = choose_device(args.device)

    dataset = MirrorSceneDataset(
        args.data_dir,
        num_views=args.num_views,
        img_size=args.img_size,
        split=args.split,
        max_scenes=args.max_scenes,
    )

    if len(dataset) == 0:
        result = empty_result(args, device)
        write_json(args.output_json, result)
        write_note(args.output_note, result)
        print(json.dumps(result, indent=2))
        if not args.allow_empty:
            raise SystemExit(2)
        return

    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        collate_fn=collate_fn,
        pin_memory=(device.type == "cuda"),
    )

    model = DualHeadVGGT(args.pretrained_name, freeze_encoder=True).to(device)
    checkpoint_load = load_dual_checkpoint(model, args.checkpoint, device)
    model.eval()

    results = evaluate_checkpoint(model, loader, device, args.mask_threshold)
    reference_metrics = load_reference_metrics(args.reference_json)
    derived = compare_to_reference(
        results["metrics"],
        results["coverage"],
        reference_metrics,
        args.max_reference_ratio,
        args.min_nl_pixels,
        args.min_pred_to_gt_nl_fraction_ratio,
    )
    derived.update(results["coverage"])

    output = {
        "created": datetime.now().isoformat(timespec="seconds"),
        "status": "complete",
        "data_dir": args.data_dir,
        "num_scenes": len(dataset),
        "num_views": args.num_views,
        "batch_size": args.batch_size,
        "device": str(device),
        "pretrained_name": args.pretrained_name,
        "checkpoint": args.checkpoint,
        "checkpoint_load": checkpoint_load,
        "reference_json": args.reference_json,
        **results,
        "derived": derived,
    }
    write_json(args.output_json, output)
    write_note(args.output_note, output)
    print(json.dumps(output, indent=2))


def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate Phase 0.5 dual-head checkpoint.")
    parser.add_argument("--data_dir", type=str, required=True)
    parser.add_argument("--checkpoint", type=str, default="checkpoints/phase05_dual_head/dual_head_final.pt")
    parser.add_argument("--reference_json", type=str, default=None)
    parser.add_argument("--pretrained_name", type=str, default="facebook/VGGT-1B")
    parser.add_argument("--num_views", type=int, default=8)
    parser.add_argument("--img_size", type=int, default=518)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--max_scenes", type=int, default=None)
    parser.add_argument("--split", type=str, default="eval")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--device", type=str, default="auto")
    parser.add_argument("--mask_threshold", type=float, default=0.5)
    parser.add_argument("--max_reference_ratio", type=float, default=2.0)
    parser.add_argument("--min_nl_pixels", type=int, default=1000)
    parser.add_argument("--min_pred_to_gt_nl_fraction_ratio", type=float, default=0.25)
    parser.add_argument("--allow_empty", action="store_true")
    parser.add_argument("--output_json", type=str, default="notes/20-Experiments/phase05_dual_head_cross_domain.json")
    parser.add_argument("--output_note", type=str, default="notes/20-Experiments/Phase-0.5-Dual-Head-Cross-Domain.md")
    return parser.parse_args()


if __name__ == "__main__":
    run(parse_args())
